// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaOw8Bh9YY2bBoslwk1Rlu_8C7KR-g0Lk',
    appId: '1:1020891925567:web:a904ed814909dc2c953c8a',
    messagingSenderId: '1020891925567',
    projectId: 'yatrik-baaa3',
    authDomain: 'yatrik-baaa3.firebaseapp.com',
    storageBucket: 'yatrik-baaa3.firebasestorage.app',
    measurementId: 'G-467CWPBG33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_C4urwXO4G9OZ2su334vLFMyr6tR8gU',
    appId: '1:1020891925567:android:a39f54602dcdaa6b953c8a',
    messagingSenderId: '1020891925567',
    projectId: 'yatrik-baaa3',
    storageBucket: 'yatrik-baaa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2vsNrks4ii_0sArOtv6NJbrq6QsHcT0',
    appId: '1:1020891925567:ios:9b42850b9325e5a5953c8a',
    messagingSenderId: '1020891925567',
    projectId: 'yatrik-baaa3',
    storageBucket: 'yatrik-baaa3.firebasestorage.app',
    androidClientId: '1020891925567-5e49fkma05s89o84t3omin96khlo8uib.apps.googleusercontent.com',
    iosClientId: '1020891925567-rtpmh2bkcq56ag798ib064qtck6f2nk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2vsNrks4ii_0sArOtv6NJbrq6QsHcT0',
    appId: '1:1020891925567:ios:9b42850b9325e5a5953c8a',
    messagingSenderId: '1020891925567',
    projectId: 'yatrik-baaa3',
    storageBucket: 'yatrik-baaa3.firebasestorage.app',
    androidClientId: '1020891925567-5e49fkma05s89o84t3omin96khlo8uib.apps.googleusercontent.com',
    iosClientId: '1020891925567-rtpmh2bkcq56ag798ib064qtck6f2nk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaOw8Bh9YY2bBoslwk1Rlu_8C7KR-g0Lk',
    appId: '1:1020891925567:web:6cd6b62bb9266cc1953c8a',
    messagingSenderId: '1020891925567',
    projectId: 'yatrik-baaa3',
    authDomain: 'yatrik-baaa3.firebaseapp.com',
    storageBucket: 'yatrik-baaa3.firebasestorage.app',
    measurementId: 'G-5MLXJYSNPT',
  );

}